### ISSUE TITLE
NoSuchBeanException when converting to use micronaut-spring on existing spring project

### ISSUE THREAD

**Issue by thedewpoint** [micronaut-projects/micronaut-spring#126]
I recently converted a sample service using spring boot over to use micronaut spring. I was able to get my healthcheck endpoint working, but in order to do it I had to comment out the below injection. Any direction on how to troubleshoot this would be appreciated. I'm getting a similar endpoint that injects aws java sdk dynamodb query utils class, so I'm wondering if there are certain spring beans that cannot be converted to be used within micronaut?

EDIT:
I tried autowiring RestTemplate into the greeter service in this examples folder, and I received the same error, so I don't think it's an issue with my project configuration but I'm not entirely sure.

```import org.springframework.web.client.RestTemplate;

// @Autowired
// RestTemplate restTemplate;

```
Otherwise I face this error:
```
{"message":"Internal Server Error: Failed to inject value for field [restTemplate] of class: com.company.webservice.resource.$HealthCheckResourceDefinition$Intercepted\r\n\r\nPath Taken: $HealthCheckResourceDefinition$Intercepted.restTemplate"}


ERROR io.micronaut.http.server.netty.RoutingInBoundHandler - Unexpected error occurred: Failed to inject value for field [restTemplate] of class: com.company.resource.$HealthCheckResourceDefinition$Intercepted

Path Taken: $HealthCheckResourceDefinition$Intercepted.restTemplate
io.micronaut.context.exceptions.DependencyInjectionException: Failed to inject value for field [restTemplate] of class: com.company.webservice.resource.$HealthCheckResourceDefinition$Intercepted

Path Taken: $HealthCheckResourceDefinition$Intercepted.restTemplate
        at io.micronaut.context.AbstractBeanDefinition.getBeanForField(AbstractBeanDefinition.java:1419)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForField(AbstractBeanDefinition.java:1184)
        at com.company.webservice.resource.$HealthCheckResourceDefinition.injectBean(Unknown Source)
        at com.company.webservice.resource.$$HealthCheckResourceDefinition$InterceptedDefinition.injectBean(Unknown Source)
        at com.company.webservice.resource.$$HealthCheckResourceDefinition$InterceptedDefinition.build(Unknown Source)
        at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1693)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingletonInternal(DefaultBeanContext.java:2407)
        at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:2393)
        at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:2084)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2058)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:618)
        at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.getTarget(DefaultBeanContext.java:2972)
        at io.micronaut.context.DefaultBeanContext$BeanExecutionHandle.invoke(DefaultBeanContext.java:2993)
        at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:228)
        at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:122)
        at io.micronaut.http.server.netty.RoutingInBoundHandler.lambda$buildResultEmitter$16(RoutingInBoundHandler.java:1474)
        at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:37)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.internal.operators.flowable.FlowableSwitchIfEmpty.subscribeActual(FlowableSwitchIfEmpty.java:32)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14868)
        at io.micronaut.core.async.publisher.Publishers.lambda$map$2(Publishers.java:134)
        at io.micronaut.http.context.ServerRequestTracingPublisher.lambda$subscribe$0(ServerRequestTracingPublisher.java:52)
        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:68)
        at io.micronaut.http.context.ServerRequestTracingPublisher.subscribe(ServerRequestTracingPublisher.java:52)
        at io.reactivex.internal.operators.flowable.FlowableFromPublisher.subscribeActual(FlowableFromPublisher.java:29)
        at io.reactivex.Flowable.subscribe(Flowable.java:14918)
        at io.reactivex.Flowable.subscribe(Flowable.java:14865)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:288)
        at io.reactivex.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:253)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.micronaut.context.exceptions.NoSuchBeanException: No bean of type [org.springframework.web.client.RestTemplate] exists. Make sure the bean is not disabled by bean requirements (enable trace logging for 'io.micronaut.context.condition' to check) and if the bean is enabled then ensure the class is declared a bean and annotation processing is enabled (for Java and Kotlin the 'micronaut-inject-java' dependency should be configured as an annotation processor).
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2069)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1095)
        at io.micronaut.context.AbstractBeanDefinition.getBeanForField(AbstractBeanDefinition.java:1411)
        ... 35 common frames omitted
10:16:58.536 [nioEventLoopGroup-1-2] DEBUG io.micronaut.http.server.netty.RoutingInBoundHandler - Encoding emitted response object [Internal Server Error: Failed to inject value for field [restTemplate] of class: com.company.webservice.resource.$HealthCheckResourceDefinition$Intercepted
```

**Comment by thedewpoint** [comment]
@ilopmar Do you think you could direct me on how to debug this?

**Comment by graemerocher** [comment]
`RestTemplate` is not a bean in Micronaut, you would need to define it yourself. Something like:

```
@Factory
class RestTemplateFactory {
    @Singleton
     RestTemplate restTemplate() {
          return new RestTemplate();
     }
 
}
```

**Comment by thedewpoint** [comment]
@graemerocher  thank you for the swift reply. Would this be the case for any bean that I wanted to use? for example I have this other dynamodb bean
```
import com.amazonaws.services.dynamodbv2.document.DynamoDB;

@Autowired
private DynamoDB dynamoDB;
```
I thought that the annotation processor looked for anything being autowired and created beans for them. Is there any way to do this automatically for beans that are not inherently part of micronaut?

**Comment by graemerocher** [comment]
there currently is not no. If you want DynamoDB see https://micronaut-projects.github.io/micronaut-aws/latest/guide/#dynamodb which you can add to your classpath

**Comment by thedewpoint** [comment]
@graemerocher appreciate it, thank you. My hope was to have a minimally invasive way to take advantage of micronaut by using micronaut-spring, but it seems I may have to do a lot of code refactoring in order to do this, unless I misunderstand. Thanks again for your help.

**Comment by graemerocher** [comment]
yes as mentioned in the project description this project allows you to use Spring annotations but at runtime it is a Micronaut application so you will need to use the Micronaut equivalents of various libraries (such as `micronaut-aws` for dynamodb)

**Comment by thedewpoint** [comment]
@graemerocher appreciate it, thanks again!!
