### ISSUE TITLE
getBean("name") throws NullPointerException if the bean is not found

### ISSUE THREAD

**Issue by longwa** [micronaut-projects/micronaut-spring#14]
Using Grails 4.0.0.M1, if a bean is attempted to be loaded via `getBean('foo')` or using the BeanBuilder syntax of `ref('foo')`, a NullPointerException is thrown from the MicronautBeanFactory.
```
ava.lang.NullPointerException: null
        at io.micronaut.context.DefaultBeanContext.lambda$findBeanCandidates$29(DefaultBeanContext.java:1203)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
        at java.util.concurrent.ConcurrentLinkedQueue$CLQSpliterator.forEachRemaining(ConcurrentLinkedQueue.java:857)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at io.micronaut.context.DefaultBeanContext.findBeanCandidates(DefaultBeanContext.java:1223)
Comment
        at io.micronaut.context.DefaultApplicationContext.findBeanCandidates(DefaultApplicationContext.java:196)
        at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:1834)
        at io.micronaut.context.DefaultBeanContext.lambda$findConcreteCandidate$50(DefaultBeanContext.java:1829)
        at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.lambda$compute$0(ConcurrentLinkedHashMap.java:721)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1688)
        at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.compute(ConcurrentLinkedHashMap.java:733)
        at io.micronaut.core.util.clhm.ConcurrentLinkedHashMap.computeIfAbsent(ConcurrentLinkedHashMap.java:710)
        at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:1828)
        at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1624)
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:533)
        at io.micronaut.spring.context.factory.MicronautBeanFactory.doGetBean(MicronautBeanFactory.java:640)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:273)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1105)
        at contextnullpointer.Application$_doWithSpring_closure1.doCall(Application.groovy:20)
```

I believe it should throw a `NoSuchBeanDefinitionException` instead.

Sample Grails 4 application (sorry, no Micronaut example):
https://github.com/longwa/grails4-contextNullPointer

**Comment by graemerocher** [comment]
Thanks for the report! Will fix this
