### ISSUE TITLE
Failing context lookup/binding from MicronautApplicationContext.getBeansOfType 

### ISSUE THREAD

**Issue by frehov** [micronaut-projects/micronaut-spring#246]
### Expected Behavior

When using the application context to lookup beans of a certain type, I expect to get all beans associated with that type.

### Actual Behaviour

1. When using the (micronaut-core) application context to lookup beans of a certain type, I get all beans associated with a certain type regardless of them having a named annotation or not.
2. When using the (micronaut-spring) application context to lookup beans of a certain type, I get a NoSuchBeanException if the bean I'm looking up is multiple named beans.

### Steps To Reproduce

1. Create a `ConfigurationProperty`-class annotated with `@EachProperty("a.b")` and `@Context` the class should receive the named parameter in it's constructor
2. Create an `ApplicationEventListener<StartupEvent>` and inject both micronaut and spring application contexts
3. add properties `a.b.a`, `a.b.b`, `a.b.c` to application.yml
3. With the micronaut application context call `micronautContext.getBeansOfType(Config.class)` and get 3 configuration class beans.
4. With the spring adapted application context (MicronautApplicationContext class) call `springContext.getBeansOfType(Config.class)` and get a `NoSuchBeanException` with a message `"No bean named 'Config(a)' available"` (there might be a variation of either a, b or c as the name.)

### Environment Information

- WIndows 10 - Latest update
- OpenJDK 16.
- Kotlin 1.5.31
- Gradle 7.2
- Micronaut-bom 3.2.1

### Version

3.2.1

**Comment by graemerocher** [comment]
Please provide an example that reproduces the problem

**Comment by frehov** [comment]
@graemerocher I've added an example in the original submisson, but for brewity here's the link https://github.com/frehov/micronaut-spring-failing-context-lookup-demo

The code doing the lookup through context is in the `StartupListener` class, I've also added a third example which is using the Spring BeanFactoryUtils

The exception thrown is `NoSuchBeanDefinitionException` and not `NoSuchBeanException`, I've also updated to micronaut 3.2.2, but the issue is present in 3.2.0 and 3.2.1 as well.

**Comment by ojebari-ma** [comment]
Can you please confirm that this is still an issue in the latest version of Micronaut?

**Comment by frehov** [comment]
@ojebari-ma I'm going to need a frame of reference for what's expected here after all these years

- Which Java version should be used? 16, 17, 21 or 24?
- Which kotlin version should be used? Kotlin 1.9 or 2.1?
- Which version of Gradle should be used? 8?

**Comment by frehov** [comment]
@ojebari-ma short answer is yes, this is still an issue as far as I can tell.
I'm also open to me being the ass and using the framework wrong ;)

Updated configuration:
- WIndows 11 - 24H2 (OS Build: 26100.4061)
- AdoptOpenJDK 17 and 21.
- Kotlin 1.9.25
- Gradle 8.14.1
- Micronaut-platform 4.8.2

I've update the example that reproduces this, and I'm getting the same output on java 17 and java 21.

```log
01:22:31.585 [main] INFO  c.e.m.spring.StartupListener - Step 1: app1 - DemoConfig(serviceId='app1', jms=JmsConfig(topicName=VirtualTopic.36e9c15ba0, brokerUrl=vm://local-1))
01:22:31.588 [main] INFO  c.e.m.spring.StartupListener - Step 1: app2 - DemoConfig(serviceId='app2', jms=JmsConfig(topicName=VirtualTopic.72dae7ed7e, brokerUrl=vm://local-2))
01:22:31.588 [main] INFO  c.e.m.spring.StartupListener - Step 1: app3 - DemoConfig(serviceId='app3', jms=JmsConfig(topicName=VirtualTopic.30d0084ec1, brokerUrl=vm://local-3))
01:22:31.588 [main] INFO  c.e.m.spring.StartupListener - Step 1.5: DemoConfig(serviceId='app1', jms=JmsConfig(topicName=VirtualTopic.36e9c15ba0, brokerUrl=vm://local-1))
01:22:31.595 [main] ERROR c.e.m.spring.StartupListener - Step 2: Could not look up beans through spring adapted context
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'com.example.micronuaut.spring.DemoConfig(app1)' available
	at io.micronaut.spring.context.factory.MicronautBeanFactory.getBean(MicronautBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:695)
	at io.micronaut.spring.context.factory.MicronautBeanFactory.getBeansOfType(MicronautBeanFactory.java:539)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:683)
	at io.micronaut.spring.context.MicronautApplicationContext.getBeansOfType(MicronautApplicationContext.java:208)
	at com.example.micronuaut.spring.StartupListener.onApplicationEvent(StartupListener.kt:35)
	at com.example.micronuaut.spring.StartupListener.onApplicationEvent(StartupListener.kt:13)
	at io.micronaut.context.event.ApplicationEventPublisherFactory.notifyEventListeners(ApplicationEventPublisherFactory.java:266)
	at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:226)
	at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1865)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:368)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:225)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:75)
	at com.example.micronuaut.spring.Application.main(Application.kt:19)
01:22:31.597 [main] ERROR c.e.m.spring.StartupListener - Step 3: Could not look up beans through spring adapted context using BeanFactoryUtils
org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'com.example.micronuaut.spring.DemoConfig(app1)' available
	at io.micronaut.spring.context.factory.MicronautBeanFactory.getBean(MicronautBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:695)
	at io.micronaut.spring.context.factory.MicronautBeanFactory.getBeansOfType(MicronautBeanFactory.java:539)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeansOfType(DefaultListableBeanFactory.java:683)
	at io.micronaut.spring.context.MicronautApplicationContext.getBeansOfType(MicronautApplicationContext.java:208)
	at org.springframework.beans.factory.BeanFactoryUtils.beansOfTypeIncludingAncestors(BeanFactoryUtils.java:321)
	at com.example.micronuaut.spring.StartupListener.onApplicationEvent(StartupListener.kt:46)
	at com.example.micronuaut.spring.StartupListener.onApplicationEvent(StartupListener.kt:13)
	at io.micronaut.context.event.ApplicationEventPublisherFactory.notifyEventListeners(ApplicationEventPublisherFactory.java:266)
	at io.micronaut.context.event.ApplicationEventPublisherFactory$2.publishEvent(ApplicationEventPublisherFactory.java:226)
	at io.micronaut.context.DefaultBeanContext.publishEvent(DefaultBeanContext.java:1865)
	at io.micronaut.context.DefaultBeanContext.start(DefaultBeanContext.java:368)
	at io.micronaut.context.DefaultApplicationContext.start(DefaultApplicationContext.java:225)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:75)
	at com.example.micronuaut.spring.Application.main(Application.kt:19)
01:22:31.963 [main] INFO  io.micronaut.runtime.Micronaut - Startup completed in 1054ms. Server Running: http://localhost:8080

```
