### ISSUE TITLE
io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [java.util.concurrent.ExecutorService, java.util.concurrent.ExecutorService]

### ISSUE THREAD

**Issue by donbeave** [micronaut-projects/micronaut-spring#292]
### Actual Behaviour

One of my private Spring Boot applications is not able to upgrade to the latest Spring Boot version 2.6.6, it looks like the problem is not on the Spring Boot side, but probably on the `micronaut-spring` library side.

The application failed to start with this error:

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.actuate.autoconfigure.metrics.task.TaskExecutorMetricsAutoConfiguration': Unsatisfied dependency expressed through method 'bindTaskExecutorsToRegistry' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'java.util.concurrent.ExecutorService': FactoryBean threw exception on object creation; nested exception is io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [java.util.concurrent.ExecutorService, java.util.concurrent.ExecutorService]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.resolveMethodArguments(AutowiredAnnotationBeanPostProcessor.java:767)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.inject(AutowiredAnnotationBeanPostProcessor.java:719)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:740)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:415)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301)
	at ***.***.***.***.***Application.main(***Application.java:62)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'java.util.concurrent.ExecutorService': FactoryBean threw exception on object creation; nested exception is io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [java.util.concurrent.ExecutorService, java.util.concurrent.ExecutorService]
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:176)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:101)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1884)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.getObjectForBeanInstance(AbstractAutowireCapableBeanFactory.java:1284)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:267)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1607)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1571)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveMultipleBeans(DefaultListableBeanFactory.java:1490)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1347)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredMethodElement.resolveMethodArguments(AutowiredAnnotationBeanPostProcessor.java:759)
	... 20 common frames omitted
Caused by: io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [java.util.concurrent.ExecutorService, java.util.concurrent.ExecutorService]
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:2429)
	at io.micronaut.context.DefaultApplicationContext.findConcreteCandidate(DefaultApplicationContext.java:455)
	at io.micronaut.context.DefaultBeanContext.lastChanceResolve(DefaultBeanContext.java:3253)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:3140)
	at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:3054)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:2750)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1704)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:1678)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:905)
	at io.micronaut.context.BeanLocator.findBean(BeanLocator.java:291)
	at io.micronaut.spring.beans.MicronautSpringBeanFactory.getObject(MicronautSpringBeanFactory.java:61)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:169)
	... 32 common frames omitted
```

It looks like Micronaut registering two beans of `ExecutorService` type. I have tried to find related logs, if I didn't misread them it shows me that two beans was registered by using `ExecutorFactory`.

```
2022-04-01 22:21:49.339 DEBUG 37467 --- [           main] io.micronaut.context.DefaultBeanContext  : Finding candidate beans for type: ExecutorService
2022-04-01 22:21:49.339 DEBUG 37467 --- [           main] io.micronaut.context.DefaultBeanContext  : Resolved bean candidates [Definition: io.micronaut.scheduling.executor.ExecutorFactory, Definition: io.micronaut.http.netty.channel.DefaultEventLoopGroupRegistry] for type: ExecutorService
2022-04-01 22:21:49.339 DEBUG 37467 --- [           main] io.micronaut.context.DefaultBeanContext  : Finding candidate beans for type: ExecutorConfiguration
2022-04-01 22:21:49.339 DEBUG 37467 --- [           main] io.micronaut.context.DefaultBeanContext  : Resolved bean candidates [Definition: io.micronaut.scheduling.executor.ScheduledExecutorServiceConfig, Definition: io.micronaut.scheduling.executor.UserExecutorConfiguration, Definition: io.micronaut.scheduling.executor.IOExecutorServiceConfig] for type: ExecutorConfiguration
2022-04-01 22:21:49.339 DEBUG 37467 --- [           main] io.micronaut.context.DefaultBeanContext  : Finalized bean definitions candidates: [Definition: io.micronaut.scheduling.executor.ScheduledExecutorServiceConfig, Definition: io.micronaut.scheduling.executor.IOExecutorServiceConfig]
2022-04-01 22:21:49.339 DEBUG 37467 --- [           main] io.micronaut.context.DefaultBeanContext  : Finding candidate beans for type: EventLoopGroupConfiguration
2022-04-01 22:21:49.339 DEBUG 37467 --- [           main] io.micronaut.context.DefaultBeanContext  : Resolved bean candidates [Definition: io.micronaut.http.netty.channel.DefaultEventLoopGroupConfiguration] for type: EventLoopGroupConfiguration
2022-04-01 22:21:49.339 DEBUG 37467 --- [           main] io.micronaut.context.DefaultBeanContext  : Finalized bean definitions candidates: []
2022-04-01 22:21:49.339 DEBUG 37467 --- [           main] io.micronaut.context.DefaultBeanContext  : Finalized bean definitions candidates: [Definition: io.micronaut.scheduling.executor.ExecutorFactory, Definition: io.micronaut.scheduling.executor.ExecutorFactory]
2022-04-01 22:21:49.339 DEBUG 37467 --- [           main] io.micronaut.context.DefaultBeanContext  : Searching for @Primary for type [ExecutorService] from candidates: [Definition: io.micronaut.scheduling.executor.ExecutorFactory, Definition: io.micronaut.scheduling.executor.ExecutorFactory] 
2022-04-01 22:21:49.340  WARN 37467 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.actuate.autoconfigure.metrics.task.TaskExecutorMetricsAutoConfiguration': Unsatisfied dependency expressed through method 'bindTaskExecutorsToRegistry' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'java.util.concurrent.ExecutorService': FactoryBean threw exception on object creation; nested exception is io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [java.util.concurrent.ExecutorService, java.util.concurrent.ExecutorService]
```

Probably one of `ExecutorService` is `scheduled` and another one is `io`:

<img width="1655" alt="CleanShot 2022-04-02 at 06 30 24@2x" src="https://user-images.githubusercontent.com/139017/161350319-5083cd71-6ac1-49b1-95ba-6f40270cf98d.png">

### Steps To Reproduce

I'm unable to provide the sample application, which will reproduce this error. I'm happy to provide any required information (like logs, debug, etc) to be able to investigate this bug and found the root of the problem.

### Environment Information

Spring Boot: 2.6.6
Micronaut: 3.4.1
Micronaut Spring: 4.1.0

### Version

3.4.1

**Comment by graemerocher** [comment]
can you provide an example app?
