### ISSUE TITLE
java.lang.ClassNotFoundException: org.springframework.http.server.reactive.ServerHttpRequest

### ISSUE THREAD

**Issue by davidkiss** [micronaut-projects/micronaut-spring#35]
I'm trying to convert a Spring Boot v1.5.2 application to micronaut and following the guide (https://micronaut-projects.github.io/micronaut-spring/latest/guide/index.html) and the sample app (https://github.com/micronaut-projects/micronaut-spring/tree/master/examples/greeting-service) and getting below exception:

```
2019-07-31T14:11:22,282-05:00 [main] ERROR io.micronaut.runtime.Micronaut - Error starting Micronaut server: Error instantiating bean of type  [io.micronaut.http.bind.DefaultRequestBinderRegistry]

Message: org/springframework/http/server/reactive/ServerHttpRequest
Path Taken: new NettyHttpServer(NettyHttpServerConfiguration serverConfiguration,ApplicationContext applicationContext,Router router,[RequestArgumentSatisfier requestArgumentSatisfier],MediaTypeCodecRegistry mediaTypeCodecRegistry,NettyCustomizableResponseTypeHandlerRegistry customizableResponseTypeHandlerRegistry,StaticResourceResolver resourceResolver,ExecutorService ioExecutor,ThreadFactory threadFactory,ExecutorSelector executorSelector,NettyServerSslBuilder nettyServerSslBuilder,List outboundHandlers) --> new NettyRequestArgumentSatisfier([RequestBinderRegistry requestBinderRegistry]) --> new DefaultRequestBinderRegistry(ConversionService conversionService,[List binders])
io.micronaut.context.exceptions.BeanInstantiationException: Error instantiating bean of type  [io.micronaut.http.bind.DefaultRequestBinderRegistry]

Message: org/springframework/http/server/reactive/ServerHttpRequest
Path Taken: new NettyHttpServer(NettyHttpServerConfiguration serverConfiguration,ApplicationContext applicationContext,Router router,[RequestArgumentSatisfier requestArgumentSatisfier],MediaTypeCodecRegistry mediaTypeCodecRegistry,NettyCustomizableResponseTypeHandlerRegistry customizableResponseTypeHandlerRegistry,StaticResourceResolver resourceResolver,ExecutorService ioExecutor,ThreadFactory threadFactory,ExecutorSelector executorSelector,NettyServerSslBuilder nettyServerSslBuilder,List outboundHandlers) --> new NettyRequestArgumentSatisfier([RequestBinderRegistry requestBinderRegistry]) --> new DefaultRequestBinderRegistry(ConversionService conversionService,[List binders])
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1333)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1902)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1623)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1603)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:885)
Disconnected from the target VM, address: '127.0.0.1:63967', transport: 'socket'
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:978)
	at io.micronaut.http.server.netty.$NettyRequestArgumentSatisfierDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1319)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1902)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1623)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1603)
	at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:885)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:978)
	at io.micronaut.http.server.netty.$NettyHttpServerDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1319)
	at io.micronaut.context.DefaultBeanContext.createAndRegisterSingleton(DefaultBeanContext.java:1902)
	at io.micronaut.context.DefaultBeanContext.getBeanForDefinition(DefaultBeanContext.java:1623)
	at io.micronaut.context.DefaultBeanContext.getBeanInternal(DefaultBeanContext.java:1603)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:903)
	at io.micronaut.context.DefaultBeanContext.findBean(DefaultBeanContext.java:506)
	at io.micronaut.context.BeanLocator.findBean(BeanLocator.java:133)
	at io.micronaut.runtime.Micronaut.start(Micronaut.java:69)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:274)
	at io.micronaut.runtime.Micronaut.run(Micronaut.java:260)
	at com.loblaw.loyalty.api.inquiry.InquiryServiceApplication.main(InquiryServiceApplication.java:55)
Caused by: java.lang.NoClassDefFoundError: org/springframework/http/server/reactive/ServerHttpRequest
	at io.micronaut.spring.web.bind.$ServerHttpRequestBinderDefinition.getTypeArgumentsMap(Unknown Source)
	at io.micronaut.context.AbstractBeanDefinition.getTypeArguments(AbstractBeanDefinition.java:211)
	at io.micronaut.inject.BeanDefinition.getTypeArguments(BeanDefinition.java:194)
	at io.micronaut.inject.BeanDefinition.getTypeParameters(BeanDefinition.java:206)
	at io.micronaut.inject.BeanDefinition.getTypeParameters(BeanDefinition.java:218)
	at io.micronaut.context.DefaultBeanContext$BeanKey.<init>(DefaultBeanContext.java:2471)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1277)
	at io.micronaut.context.DefaultBeanContext.addCandidateToList(DefaultBeanContext.java:2238)
	at io.micronaut.context.DefaultBeanContext.getBeansOfTypeInternal(DefaultBeanContext.java:2166)
	at io.micronaut.context.DefaultBeanContext.getBeansOfType(DefaultBeanContext.java:754)
	at io.micronaut.context.AbstractBeanDefinition.lambda$getBeansOfTypeForConstructorArgument$10(AbstractBeanDefinition.java:1084)
	at io.micronaut.context.AbstractBeanDefinition.resolveBeanWithGenericsFromConstructorArgument(AbstractBeanDefinition.java:1680)
	at io.micronaut.context.AbstractBeanDefinition.getBeansOfTypeForConstructorArgument(AbstractBeanDefinition.java:1079)
	at io.micronaut.context.AbstractBeanDefinition.getBeanForConstructorArgument(AbstractBeanDefinition.java:958)
	at io.micronaut.http.bind.$DefaultRequestBinderRegistryDefinition.build(Unknown Source)
	at io.micronaut.context.DefaultBeanContext.doCreateBean(DefaultBeanContext.java:1319)
	... 24 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.springframework.http.server.reactive.ServerHttpRequest
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 40 common frames omitted
```

From what I can see, micronaut's `io.micronaut.spring.web.bind.ServerHttpRequestBinder` class depends on Spring webflux code (`import org.springframework.http.server.reactive.ServerHttpRequest;`), but my Spring Boot app doesn't use webflux at all.

I'm wondering if the `ServerHttpRequestBinder` bean should only be initialized, if webflux is on the classpath? Or am I missing something?

**Comment by ilopmar** [comment]
@davidkiss can you please share an application that reproduces the issue?

**Comment by davidkiss** [comment]
@ilopmar I no longer have access to the code where I tried using micronaut so won't be able to reproduce this issue. Feel free to close the ticket, if that's a blocker
