### ISSUE TITLE
Spring-boot micronaut-data application fails with Multiple possible bean candidate exception

### ISSUE THREAD

**Issue by timyates** [micronaut-projects/micronaut-spring#383]
We have a guide for using micronaut-data along with spring-boot.

https://github.com/micronaut-projects/micronaut-guides/tree/master/guides/spring-boot-micronaut-data

Since the release of Micronaut 3.8.0 (which references `micronaut-spring-boot-starter:4.4.0` in the BOM), this guide fails to build with:

```
io.micronaut.context.exceptions.NonUniqueBeanException: Multiple possible bean candidates found: [io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations, io.micronaut.data.jdbc.operations.DefaultJdbcRepositoryOperations]
        at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:2472) ~[micronaut-inject-3.8.0.jar:3.8.0]
        at io.micronaut.context.DefaultApplicationContext.findConcreteCandidate(DefaultApplicationContext.java:488) ~[micronaut-inject-3.8.0.jar:3.8.0]
        at io.micronaut.context.DefaultBeanContext.lastChanceResolve(DefaultBeanContext.java:3249) ~[micronaut-inject-3.8.0.jar:3.8.0]
        at io.micronaut.context.DefaultBeanContext.findConcreteCandidateNoCache(DefaultBeanContext.java:3140) ~[micronaut-inject-3.8.0.jar:3.8.0]
        at io.micronaut.context.DefaultBeanContext.findConcreteCandidate(DefaultBeanContext.java:3058) ~[micronaut-inject-3.8.0.jar:3.8.0]
        at io.micronaut.context.DefaultBeanContext.findBeanDefinition(DefaultBeanContext.java:788) ~[micronaut-inject-3.8.0.jar:3.8.0]
        at io.micronaut.context.DefaultBeanContext.resolveBeanRegistration(DefaultBeanContext.java:2790) ~[micronaut-inject-3.8.0.jar:3.8.0]
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:1617) ~[micronaut-inject-3.8.0.jar:3.8.0]
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:867) ~[micronaut-inject-3.8.0.jar:3.8.0]
        at io.micronaut.context.DefaultBeanContext.getBean(DefaultBeanContext.java:859) ~[micronaut-inject-3.8.0.jar:3.8.0]
        at io.micronaut.data.runtime.operations.DefaultRepositoryOperationsRegistry.provide(DefaultRepositoryOperationsRegistry.java:53) ~[micronaut-data-runtime-3.9.1.jar:3.9.1]
        at io.micronaut.data.runtime.intercept.DataInterceptorResolver.findInterceptor(DataInterceptorResolver.java:111) ~[micronaut-data-runtime-3.9.1.jar:3.9.1]
        at io.micronaut.data.runtime.intercept.DataInterceptorResolver.lambda$resolve$2(DataInterceptorResolver.java:92) ~[micronaut-data-runtime-3.9.1.jar:3.9.1]
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708) ~[na:na]
```

https://ge.micronaut.io/s/ggpqezvafcamc/console-log?task=:springBootMicronautDataRunTestScript

If I change the generated project to use

```
    implementation("io.micronaut.spring:micronaut-spring-boot-starter:4.3.1")
```

Then it works as expected, so it must be something introduced in 4.4.0

### Steps to reproduce

- Check out the [micronaut-guides project](https://github.com/micronaut-projects/micronaut-guides)
- Run `./gradlew :springBootMicronautDataRunTestScript` to see the failure
- Open `build/code/spring-boot-micronaut-data/spring-boot-micronaut-data-gradle-java` in intellij
- Change the build file to use 4.3.1 `implementation("io.micronaut.spring:micronaut-spring-boot-starter:4.3.1")`
- The tests should pass

**Comment by sdelamo** [comment]
is this closed via https://github.com/micronaut-projects/micronaut-spring/pull/384

**Comment by timyates** [comment]
Fixed via https://github.com/micronaut-projects/micronaut-spring/pull/384
