### ISSUE TITLE
graal-native-image branch # native image build failing

### ISSUE THREAD

**Issue by sarasgh** [micronaut-projects/micronaut-spring#47]
I am trying to create graal native image using docker on windows10 machine but it fails with out of memory errors at analysis phase which is taking unusually longer time though am running on 16G ram.. anyone able to successfully build native image from graal-native-image branch?

[greeting-service:6]    classlist:   9,908.57 ms
[greeting-service:6]        (cap):   1,165.18 ms
[greeting-service:6]        setup:   2,595.97 ms
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of io.netty.buffer.AbstractReferenceCountedByteBuf. Detailed failure reason(s): Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store.
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of io.netty.util.AbstractReferenceCounted. Detailed failure reason(s): Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store.
[greeting-service:6]     analysis: 363,775.29 ms
Fatal error: java.lang.OutOfMemoryError
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
        at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:458)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:289)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:427)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:109)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOf(Arrays.java:3308)
        at java.util.BitSet.ensureCapacity(BitSet.java:337)
        at java.util.BitSet.expandTo(BitSet.java:352)
        at java.util.BitSet.set(BitSet.java:447)
        at com.oracle.graal.pointsto.meta.AnalysisType.addTypeToAssignableLists(AnalysisType.java:434)
        at com.oracle.graal.pointsto.meta.AnalysisType.updateAssignableTypes(AnalysisType.java:387)
        at com.oracle.graal.pointsto.BigBang.checkObjectGraph(BigBang.java:602)
        at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:557)
        at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:684)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:523)
        at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:441)
        at com.oracle.svm.hosted.NativeImageGenerator$$Lambda$24/408544604.run(Unknown Source)
        at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1

**Comment by graemerocher** [comment]
You need to assign more memory to the native image process. See the GraalVM user guide
